"""
Export research reports to different formats.
All output files go to F:/research_agent/data/reports/
"""
import json
from pathlib import Path
from datetime import datetime
from typing import Dict
from loguru import logger

from core.config import settings


class ReportExporter:

    def __init__(self):
        self.reports_dir = Path(settings.REPORTS_DIR)
        self.reports_dir.mkdir(parents=True, exist_ok=True)

    def save_json(self, job_id: str, data: Dict) -> str:
        """Save full report data as JSON (already done by agent, this is for re-export)."""
        path = self.reports_dir / f"{job_id}.json"
        path.write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")
        logger.info(f"JSON report saved: {path}")
        return str(path)

    def export_markdown(self, job_id: str) -> str:
        """Convert JSON report to a clean Markdown file on F drive."""
        json_path = self.reports_dir / f"{job_id}.json"
        if not json_path.exists():
            raise FileNotFoundError(f"Report not found: {json_path}")

        data = json.loads(json_path.read_text(encoding="utf-8"))
        md_path = self.reports_dir / f"{job_id}.md"

        lines = []
        lines.append(f"# Research Report: {data.get('topic', 'Unknown Topic')}\n")
        lines.append(f"**Generated:** {data.get('generated_at', '')}  ")
        lines.append(f"**Papers reviewed:** {data.get('papers_count', 0)}  ")
        lines.append(f"**Claims extracted:** {data.get('claims_count', 0)}  ")
        lines.append(f"**Contradictions found:** {data.get('contradictions_count', 0)}\n")
        lines.append("---\n")

       
        lines.append(data.get("report", "No report content."))
        lines.append("\n\n---\n")

       
        papers = data.get("top_papers", [])
        if papers:
            lines.append("## Papers Reviewed\n")
            lines.append("| # | Title | Authors | Year | Venue | Citations |")
            lines.append("|---|-------|---------|------|-------|-----------|")
            for i, p in enumerate(papers, 1):
                authors = ", ".join((p.get("authors") or [])[:2])
                if len(p.get("authors") or []) > 2:
                    authors += " et al."
                lines.append(
                    f"| {i} | {p.get('title','')[:60]} | {authors} | "
                    f"{p.get('year','')} | {p.get('venue','')} | {p.get('citation_count',0)} |"
                )
            lines.append("")

       
        contradictions = data.get("contradictions", [])
        if contradictions:
            lines.append("## Contradictions Detected\n")
            for i, c in enumerate(contradictions, 1):
                lines.append(f"### Contradiction {i} (NLI score: {c.get('nli_score',0):.0%})")
                lines.append(f"**Paper A:** {c.get('paper_a_title','')} ({c.get('paper_a_year','')})")
                lines.append(f"> {c.get('claim_a_text','')[:300]}\n")
                lines.append(f"**Paper B:** {c.get('paper_b_title','')} ({c.get('paper_b_year','')})")
                lines.append(f"> {c.get('claim_b_text','')[:300]}\n")

      
        gaps = data.get("gaps", [])
        if gaps:
            lines.append("## Research Gaps\n")
            for g in gaps:
                lines.append(
                    f"- **{g.get('topic_name','Unknown')}** "
                    f"({g.get('papers_count',0)} papers) — "
                    f"Severity: {g.get('gap_severity','?')} — "
                    f"Keywords: {', '.join(g.get('keywords',[]))}"
                )
            lines.append("")

        concepts = data.get("central_concepts", [])
        if concepts:
            lines.append("## Central Concepts (Knowledge Graph)\n")
            for c in concepts[:10]:
                lines.append(f"- **{c.get('concept','')}** — degree: {c.get('degree',0)}")
            lines.append("")

        lines.append("\n---\n*Generated by Autonomous Research Agent*")

        md_path.write_text("\n".join(lines), encoding="utf-8")
        logger.info(f"Markdown report saved: {md_path}")
        return str(md_path)

    def list_reports(self):
        """List all saved reports on F drive."""
        return [
            {
                "job_id": p.stem,
                "path": str(p),
                "size_kb": round(p.stat().st_size / 1024, 1),
                "modified": datetime.fromtimestamp(p.stat().st_mtime).isoformat(),
                "format": p.suffix.lstrip("."),
            }
            for p in sorted(self.reports_dir.glob("*.json"), key=lambda x: x.stat().st_mtime, reverse=True)
        ]
